### PR TITLE
updationg XsdParser to take into account the element group in xsd

### PR DESCRIPTION
**Pull request by agreigra**
Hello @philipsens 
I was trying to create an xml editor that provides client-side code completion based on an XSD file using Monaco and your project was very helpful. So I would like say to thank you .

Since I was using a huge xsd file, I had to modify the xsdParser slightly to take into account the group element in xsd which is used to define a group of elements to be used in complex type definitions and also adding the ability to suggest all root elements if there is the tag `<any>` in the current element and I think this might be useful for others users.

Best regards,

### CODE REVIEW

**Comment by philipsens** [comment]
Hello @agreigra,

Thank you for your contribution, the code looks great. I've never used these properties before in an XSD, would you care to share a simple XSD utilizing these features. I'd love to test it.

**Comment by agreigra** [comment]
Hello  @philipsens,

Thanks for your reply. I've just added a sample xsd to the repository if you would like to test it.

**Comment by philipsens** [comment]
Thank you, @agreigra. I learned a lot from this. In the feature, I might make a demo repo or test environment in which I will include the sample XSD.

**Comment by agreigra** [comment]
Thank you so much @philipsens.

**Pull request merged**
